image:
  file: .gitpod.Dockerfile

tasks:
  - init: |
      composer install
      cp .env.example .env
      php artisan key:generate
      php artisan migrate
      npm install
  - command: |
      php artisan serve --host=0.0.0.0

ports:
  - port: 8000
    onOpen: open-preview

vscode:
  extensions:
    - MehediDracula.php-namespace-resolver
    - mikestead.dotenv
    - bmewburn.vscode-intelephense-client
    - dbaeumer.vscode-eslint
    - esbenp.prettier-vscode
